name: Continuous Integration
on:
  push:
    branches: main
  pull_request:
    branches: ["*"]

permissions:
  contents: read

jobs:
  test:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Local Action
        id: test
        uses: ./
        with:
          go-version: "1.21"
          check-latest: true
